@startuml
'https://plantuml.com/class-diagram

ShootContext o-- AbstractShoot
AbstractShoot <|..  MobShoot
AbstractShoot <|..  SeperateShoot

class ShootContext
{
    - strategy:AbstractShoot
    + setStrategy(AbstractShoot strategy):void
    + executeStrategy(AbstractAircraft aircraft):List<AbstractBullet>
}

abstract class AbstractShoot
{
    + create(AbstractAircraft aircraft):List<AbstractBullet>
    + abstract way(List<AbstractBullet> bullets):List<AbstractBullet>

}

class MobShoot
{
    +Way(List<AbstractBullet> bullet):List<AbstractBullet>
}

class SeperateShoot
{
    +Way(List<AbstractBullet> bullet):List<AbstractBullet>
}
@enduml